import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.sass";
import { useState } from "react";
import HederNavigation from "../components/Composite/header-navigation/header-navigation";
import Welcome from "../components/Composite/welcome/welcome";
import Works from "../components/Composite/works/works";
import Message from "../components/Composite/message/message";
import About from "../components/Composite/about/about";
export default function Home() {
  const [pageActive, SetPageActive] = useState<number>(1);

  const currentPageClickHandler = (currentPage: number) => {
    SetPageActive(currentPage);
  };

  const NavigationList = [
    { id: 1, text: "Home" },
    { id: 2, text: "Message" },
    { id: 3, text: "Projects" },
    { id: 4, text: "About" },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>REKT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headerWrapper}>
        <div className={styles.headerLogo}>
          <div className={styles.glitch} data-glitch="REKT">
            REKT
          </div>
        </div>
        <div className={styles.headerLogo}></div>
        <HederNavigation
          data={NavigationList}
          currentPage={pageActive}
          currentPageClickHandler={currentPageClickHandler}
        />
        <div className={styles.headerContact}>CONTACT</div>
      </div>
      <main className={styles.main}>
        {pageActive === 1 && <Welcome />}
        {pageActive === 2 && <Message />}
        {pageActive === 3 && <Works />}
        {pageActive === 4 && <About />}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
