import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.sass";
import { useState } from "react";
import HederNavigation from "../components/Composite/header-navigation/header-navigation";
import { NavigationList } from "./data";
import Welcome from "../components/Composite/welcome/welcome";
import Works from "../components/Composite/works/works";
export default function Home() {
  const [pageActive, SetPageActive] = useState<number>(1);

  const currentPageClickHandler = (currentPage: number) => {
    SetPageActive(currentPage);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headerWrapper}>
        <div className={styles.headerLogo}>
          <div>REKT</div>
        </div>
        <HederNavigation
          data={NavigationList}
          currentPage={pageActive}
          currentPageClickHandler={currentPageClickHandler}
        />
        <div className={styles.headerContact}>CONTACT</div>
      </div>
      <main className={styles.main}>
        {pageActive === 1 && <Welcome />}
        {pageActive === 2 && (
          <div>
            <div className={styles.message}>Simple is The Perfection</div>
          </div>
        )}
        {pageActive === 3 && <Works />}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
